"""Emit a deterministic OTEL "grounding" span for prompt-free Phase 5 execution.

Why this exists
---------------
The SESSION-level ``SqlGrounded`` LLM-judge verifies that every table/column in
the executed SQL appears in the retrieved schema context. It reads that context
from the ``{context}`` placeholder, which the AgentCore eval service builds from
the agent's OTEL spans/events emitted under the ``strands.telemetry.tracer``
scope (``body.{input,output}.messages`` shape).

The **metadata** (SemanticRAG) agent gets this for free: its Phase 5 runs a
bounded Strands execution agent, and the Strands SDK auto-instruments that model
call — the prompt (which carries the schema slice + SQL since the 2026-06-05
slice-in-span fix) lands in a harvested span.

The **VKG** (ontology) agent's Phase 5 is fully deterministic: it translates the
grounded SPARQL→SQL (Ontop) and runs it on Athena directly, with **no LLM call**,
so the SDK never emits a span and the judge sees the SQL (via ``reasoning``) but
no ontology slice to verify it against — it fails closed (scores 0.0).

This helper closes that gap by emitting a span in the **same tracer scope**
(``strands.telemetry.tracer``) using Strands' own ``Tracer.start_model_invoke_span``
/ ``end_model_invoke_span`` — so it carries the slice (as the input message) and
the executed SQL (as the output message) in whatever gen_ai semconv format the
runtime is configured for (stable on this deployment). Reusing the SDK's own
methods means we never hand-roll event names that could drift from what the eval
harvester expects.

It is **eval-only telemetry**: it spends no model tokens, changes no execution
behaviour, and is wrapped fail-soft so a tracing error can never break a query.
"""
from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


def emit_grounding_span(
    *,
    retrieved_schema: str,
    executed_sql: str,
    question: str = "",
    operation_label: str = "grounded_sql_execution",
) -> None:
    """Emit a deterministic grounding span carrying the schema slice + executed SQL.

    Creates one span under the ``strands.telemetry.tracer`` scope whose INPUT
    message carries the retrieved schema context (so ``SqlGrounded`` has
    something to verify against) and whose OUTPUT message carries the executed
    SQL. The span attaches to the current OTEL context, so it inherits the active
    ``session.id`` baggage (set by the agent entrypoint) and groups under the
    same session the SESSION-level judge scores.

    No-op (logged at debug) when there is no schema or no SQL to ground, or when
    the Strands tracer is unavailable. Fail-soft: any exception is swallowed —
    this is eval-only telemetry and must never break a live query.

    Args:
        retrieved_schema: The retrieved schema context the SQL must be grounded
            in — for VKG this is the Turtle ontology slice (``ctx.slice_text``).
        executed_sql: The SQL actually executed on Athena (the Ontop translation,
            post-repair).
        question: The natural-language question, included in the input message
            for the judge's context. Optional.
        operation_label: A short label distinguishing this span in traces.
    """
    if not retrieved_schema or not executed_sql:
        logger.debug(
            "emit_grounding_span skipped (schema=%s sql=%s)",
            bool(retrieved_schema), bool(executed_sql),
        )
        return

    try:
        # Reuse the SDK's global tracer so the span lands in the exact
        # ``strands.telemetry.tracer`` scope the eval harvester reads, and the
        # input/output messages are serialized in the SAME gen_ai semconv format
        # the runtime is configured for (set via OTEL_SEMCONV_STABILITY_OPT_IN).
        from strands.telemetry.tracer import get_tracer

        tracer = get_tracer()

        # INPUT message — the retrieved schema slice is the grounding context the
        # SqlGrounded judge verifies the SQL against. Label it read-only so a
        # human reading the trace knows it is grounding context, not an
        # instruction. (No model reads this — it is deterministic telemetry.)
        input_text = (
            "Grounding record for a deterministically-executed query "
            "(no model call). The executed SQL below was generated by translating "
            "a grounded SPARQL query (Ontop) against the retrieved ontology slice. "
            "This span exists so the SqlGrounded evaluator can verify the SQL "
            "against the slice.\n"
            f"[retrieved_schema_context]\n{retrieved_schema}\n[/retrieved_schema_context]"
            + (f"\n[question]\n{question}\n[/question]" if question else "")
        )
        input_messages = [{"role": "user", "content": [{"text": input_text}]}]
        output_message = {
            "role": "assistant",
            "content": [{"text": f"[executed_sql]\n{executed_sql}\n[/executed_sql]"}],
        }

        span = tracer.start_model_invoke_span(
            messages=input_messages,
            model_id=operation_label,
        )
        # Zero token usage — this is deterministic, prompt-free telemetry.
        tracer.end_model_invoke_span(
            span=span,
            message=output_message,
            usage={"inputTokens": 0, "outputTokens": 0, "totalTokens": 0},
            metrics={"latencyMs": 0},
            stop_reason="end_turn",
        )
    except Exception as exc:  # noqa: BLE001 — eval-only telemetry, never break a query
        logger.debug("emit_grounding_span failed (non-fatal): %s", exc)
