import { CfnOutput, StackProps, CustomResource, Duration, Stack } from 'aws-cdk-lib';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as s3vectors from 'aws-cdk-lib/aws-s3vectors';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as bedrock from 'aws-cdk-lib/aws-bedrock';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { NagSuppressions } from 'cdk-nag';
import { Construct } from 'constructs';
import * as path from 'path';

export interface BedrockKnowledgeBaseStackProps extends StackProps {
  projectName: string;
  artifactsBucket: s3.Bucket;
  autoStartIngestion?: boolean;
  /**
   * When false, the semantic-rag KB and its data source are not provisioned.
   * The ontology-patterns KB is unaffected.
   * @default false
   */
  enableSemanticRag?: boolean;
}

/**
 * Bedrock Knowledge Base Stack
 *
 * Creates two distinct Knowledge Bases backed by S3 Vectors + Titan Embed Text v2:
 *
 * 1. Ontology Patterns KB  (`ontologyPatternsKbId`)
 *    - Purpose: Help the ontology-generation agent create well-structured OWL ontologies.
 *    - Data source: `ontology-patterns/` prefix in the artifacts bucket (static design-pattern docs).
 *    - Consumers: ontology_agent (retrieve design patterns).
 *
 * 2. Semantic RAG KB  (`semanticRagKbId`)
 *    - Purpose: Help query agents understand real table data — business term aliases, column
 *      descriptions, and example queries generated by the metadata agent at runtime.
 *    - Data source: `metadata/` prefix in the artifacts bucket (runtime-generated markdown docs).
 *    - Consumers: ontology_query_agent, metadata_query_agent (retrieve semantic context).
 *    - Producer: metadata_agent (writes markdown docs; triggers re-ingestion after each update).
 */
export class BedrockKnowledgeBaseStack extends Stack {
  // ── Ontology Patterns KB ────────────────────────────────────────────────────
  public readonly ontologyPatternsKb: bedrock.CfnKnowledgeBase;
  public readonly ontologyPatternsKbId: string;
  public readonly ontologyPatternsDataSource: bedrock.CfnDataSource;

  // ── Semantic RAG KB ──────────────────────────────────────────────────────────
  public readonly semanticRagKb?: bedrock.CfnKnowledgeBase;
  public readonly semanticRagKbId?: string;
  public readonly semanticRagDataSource?: bedrock.CfnDataSource;
  public readonly semanticRagDataSourceId?: string;

  constructor(scope: Construct, id: string, props: BedrockKnowledgeBaseStackProps) {
    super(scope, id, props);

    const p = props.projectName;

    // ── 1. Ontology Patterns KB ───────────────────────────────────────────────
    // IMPORTANT: logical IDs and resource names below are intentionally preserved
    // from the original single-KB stack so that CloudFormation performs no
    // replacement on the existing knowledge base during this update.

    const opVectorBucket = this.createVectorBucket(
      `${p}-VectorBucket`,
      `${p}-vectors-${this.account}`
    );
    const opVectorIndex = this.createVectorIndex(`${p}-VectorIndex`, opVectorBucket, `${p}-idx`);
    opVectorIndex.node.addDependency(opVectorBucket);

    const opRole = this.createKbRole(
      `${p}-BedrockKnowledgeBaseRole`,
      `${p}`,
      props.artifactsBucket,
      opVectorBucket
    );
    opRole.node.addDependency(opVectorBucket);

    this.ontologyPatternsKb = new bedrock.CfnKnowledgeBase(this, 'OntologyPatternsKB', {
      name: `${p}-ontology-patterns`,
      description:
        'Ontology design patterns — used by the ontology-generation agent to create well-structured OWL ontologies.',
      roleArn: opRole.roleArn,
      knowledgeBaseConfiguration: this.vectorKbConfig(),
      storageConfiguration: this.s3VectorStorageConfig(
        opVectorBucket.attrVectorBucketArn,
        `${p}-idx`
      ),
    });
    this.ontologyPatternsKb.node.addDependency(opVectorIndex);
    this.ontologyPatternsKb.node.addDependency(opRole);
    this.ontologyPatternsKbId = this.ontologyPatternsKb.attrKnowledgeBaseId;

    this.ontologyPatternsDataSource = new bedrock.CfnDataSource(
      this,
      'OntologyPatternsDataSource',
      {
        knowledgeBaseId: this.ontologyPatternsKbId,
        dataDeletionPolicy: 'RETAIN',
        name: `${p}-ontology-patterns-ds`,
        description: 'Static ontology design-pattern documents (OWL examples, domain templates).',
        dataSourceConfiguration: {
          type: 'S3',
          s3Configuration: {
            bucketArn: props.artifactsBucket.bucketArn,
            inclusionPrefixes: ['ontology-patterns/'],
          },
        },
        // HIERARCHICAL chunking: the FIBO/FHIR/ACORD/W3C docs are deeply-nested markdown
        // (## Classes / ### <class>) and range up to ~1.2M chars — far beyond Titan v2's
        // 8,192-token embed limit, so 'NONE' (one chunk per file) silently dropped the
        // largest docs and overflowed downstream judge models. Embed small 300-token
        // children for precise retrieval, return the 1,500-token parent for full context.
        vectorIngestionConfiguration: {
          chunkingConfiguration: {
            chunkingStrategy: 'HIERARCHICAL',
            hierarchicalChunkingConfiguration: {
              overlapTokens: 60,
              levelConfigurations: [
                { maxTokens: 1500 }, // parent (layer 1) — returned to the agent
                { maxTokens: 300 }, // child (layer 2) — embedded & matched
              ],
            },
          },
        },
      }
    );
    this.ontologyPatternsDataSource.addDependency(this.ontologyPatternsKb);

    // Deploy static ontology-pattern docs and trigger initial ingestion
    new s3deploy.BucketDeployment(this, 'OntologyDocsDeployment', {
      sources: [s3deploy.Source.asset(path.join(__dirname, '../../../../data/ontology-docs'))],
      destinationBucket: props.artifactsBucket,
      destinationKeyPrefix: 'ontology-patterns/',
      prune: false,
      memoryLimit: 1024,
    });

    if (props.autoStartIngestion !== false) {
      this.createSyncTrigger(
        `${p}-OpSync`,
        this.ontologyPatternsKb.ref,
        this.ontologyPatternsDataSource.ref
      );
    }

    // ── 2. Semantic RAG KB ────────────────────────────────────────────────────

    if (props.enableSemanticRag === true) {
      const ragVectorBucket = this.createVectorBucket(
        `${p}-RagVectorBucket`,
        `${p}-rag-vectors-${this.account}`
      );
      const ragVectorIndex = this.createVectorIndex(
        `${p}-RagVectorIndex`,
        ragVectorBucket,
        `${p}-rag-idx`
      );
      ragVectorIndex.node.addDependency(ragVectorBucket);

      const ragRole = this.createKbRole(
        `${p}-SemanticRagKbRole`,
        `${p}-rag`,
        props.artifactsBucket,
        ragVectorBucket
      );
      ragRole.node.addDependency(ragVectorBucket);

      this.semanticRagKb = new bedrock.CfnKnowledgeBase(this, 'SemanticRagKB', {
        name: `${p}-semantic-rag`,
        description:
          'Semantic RAG — business term aliases, column descriptions, and example queries for actual table data. Written by the metadata agent at runtime.',
        roleArn: ragRole.roleArn,
        knowledgeBaseConfiguration: this.vectorKbConfig(),
        storageConfiguration: this.s3VectorStorageConfig(
          ragVectorBucket.attrVectorBucketArn,
          `${p}-rag-idx`
        ),
      });
      this.semanticRagKb.node.addDependency(ragVectorIndex);
      this.semanticRagKb.node.addDependency(ragRole);
      this.semanticRagKbId = this.semanticRagKb.attrKnowledgeBaseId;

      this.semanticRagDataSource = new bedrock.CfnDataSource(this, 'SemanticRagDataSource', {
        knowledgeBaseId: this.semanticRagKbId,
        dataDeletionPolicy: 'RETAIN',
        // Renamed (-h2) so the HIERARCHICAL-chunking switch can REPLACE this data
        // source: chunkingConfiguration is immutable, so CFN create-before-deletes
        // a new DataSource — Bedrock rejects a duplicate name within the KB, so the
        // replacement must carry a distinct name. The old FIXED_SIZE source
        // (…-semantic-rag-ds) is deleted after the new one is created.
        name: `${p}-semantic-rag-ds-h3`,
        description:
          'Runtime-generated metadata docs written by the metadata agent (metadata/{db}/{table}.md).',
        dataSourceConfiguration: {
          type: 'S3',
          s3Configuration: {
            bucketArn: props.artifactsBucket.bucketArn,
            inclusionPrefixes: ['metadata/'],
          },
        },
        // HIERARCHICAL chunking: a per-table metadata doc is ONE logical unit, but
        // FIXED_SIZE(512) split each into 3-5 sibling chunks that competed
        // independently for the ~20-result retrieval cap — diluting a big table's
        // signal across several vectors and letting small lexical-match docs (e.g.
        // an empty bridge table) out-rank the table that actually answers the
        // question. HIERARCHICAL embeds small precise CHILD chunks (a section:
        // Overview / Columns / Business Concepts) but returns the PARENT (the whole
        // table doc, deduped to one candidate by the topic router), so each table is
        // one retrieval unit with precise matching + full context. Parent 2000 tokens
        // holds a full table doc; child 400 ≈ one ## section. Mirrors the
        // ontology-patterns KB strategy above.
        vectorIngestionConfiguration: {
          chunkingConfiguration: {
            chunkingStrategy: 'HIERARCHICAL',
            hierarchicalChunkingConfiguration: {
              overlapTokens: 60,
              levelConfigurations: [
                { maxTokens: 2000 }, // parent (layer 1) — the full table doc, returned to the agent
                { maxTokens: 800 }, // child (layer 2) — a fuller section; 400 over-fragmented this
                // templated corpus so boilerplate sub-sections (audit cols,
                // is_deleted notes) won out — 800 keeps a section's signal intact
              ],
            },
          },
        },
      });
      this.semanticRagDataSource.addDependency(this.semanticRagKb);
      this.semanticRagDataSourceId = this.semanticRagDataSource.attrDataSourceId;
    } else {
      // Public properties remain undefined; downstream stacks must guard on enableSemanticRag.
    }

    // No deploy-time sync for Semantic RAG KB — docs are generated at runtime by
    // the metadata agent and ingestion is triggered by that agent after each write.

    // ── CloudFormation Outputs ────────────────────────────────────────────────

    new CfnOutput(this, 'OntologyPatternsKbId', {
      value: this.ontologyPatternsKbId,
      description: 'Ontology Patterns KB ID (used by ontology_agent)',
      exportName: `${p}-ontology-patterns-kb-id`,
    });
    new CfnOutput(this, 'OntologyPatternsDataSourceId', {
      value: this.ontologyPatternsDataSource.attrDataSourceId,
      description: 'Ontology Patterns KB data source ID',
    });

    if (this.semanticRagKbId !== undefined && this.semanticRagDataSourceId !== undefined) {
      new CfnOutput(this, 'SemanticRagKbId', {
        value: this.semanticRagKbId,
        description: 'Semantic RAG KB ID (used by ontology_query_agent, metadata_query_agent)',
        exportName: `${p}-semantic-rag-kb-id`,
      });
      new CfnOutput(this, 'SemanticRagDataSourceId', {
        value: this.semanticRagDataSourceId,
        description: 'Semantic RAG KB data source ID (used by metadata_agent to trigger ingestion)',
        exportName: `${p}-semantic-rag-ds-id`,
      });
    }
  }

  // ── Private helpers ──────────────────────────────────────────────────────────

  private createVectorBucket(id: string, bucketName: string): s3vectors.CfnVectorBucket {
    const bucket = new s3vectors.CfnVectorBucket(this, id, { vectorBucketName: bucketName });
    NagSuppressions.addResourceSuppressions(bucket, [
      {
        id: 'AwsSolutions-S1',
        reason:
          'S3 Vector bucket is managed by Amazon Bedrock for vector storage only. Server access logs not required.',
      },
    ]);
    return bucket;
  }

  private createVectorIndex(
    id: string,
    vectorBucket: s3vectors.CfnVectorBucket,
    indexName: string
  ): s3vectors.CfnIndex {
    return new s3vectors.CfnIndex(this, id, {
      vectorBucketName: vectorBucket.vectorBucketName!,
      indexName,
      dataType: 'float32',
      dimension: 1024, // Titan Embed Text v2
      distanceMetric: 'euclidean',
      metadataConfiguration: {
        nonFilterableMetadataKeys: ['AMAZON_BEDROCK_TEXT', 'AMAZON_BEDROCK_METADATA'],
      },
    });
  }

  private createKbRole(
    id: string,
    roleNameSuffix: string,
    dataBucket: s3.Bucket,
    vectorBucket: s3vectors.CfnVectorBucket
  ): iam.Role {
    const role = new iam.Role(this, id, {
      roleName: `AmazonBedrockExecutionRoleForKnowledgeBase-${roleNameSuffix}`.slice(0, 64),
      assumedBy: new iam.ServicePrincipal('bedrock.amazonaws.com'),
      path: '/',
    });

    // Scope the trust policy to this account and the KB resource type
    (role.node.defaultChild as iam.CfnRole).addPropertyOverride(
      'AssumeRolePolicyDocument.Statement.0.Condition',
      {
        StringEquals: { 'aws:SourceAccount': this.account },
        ArnLike: {
          'AWS:SourceArn': `arn:aws:bedrock:${this.region}:${this.account}:knowledge-base/*`,
        },
      }
    );

    // Read source documents from S3
    role.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['s3:ListBucket', 's3:GetObject'],
        resources: [dataBucket.bucketArn, `${dataBucket.bucketArn}/*`],
      })
    );

    // Read/write vectors in the dedicated vector bucket
    const vbArn = `arn:aws:s3:::${vectorBucket.vectorBucketName}`;
    role.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['s3:GetObject', 's3:PutObject', 's3:DeleteObject', 's3:ListBucket'],
        resources: [vbArn, `${vbArn}/*`],
      })
    );

    // S3 Vectors API (query and manage the vector index)
    const vbName = vectorBucket.vectorBucketName!;
    role.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['s3vectors:*'],
        resources: [
          `arn:aws:s3vectors:${this.region}:${this.account}:bucket/${vbName}`,
          `arn:aws:s3vectors:${this.region}:${this.account}:bucket/${vbName}/*`,
          `arn:aws:s3vectors:${this.region}:${this.account}:bucket/${vbName}/index/*`,
        ],
      })
    );

    // Bedrock embedding model
    role.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['bedrock:ListCustomModels'],
        resources: ['*'],
      })
    );
    role.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        // Covers both the Titan embedding model used for ingestion/query AND the
        // Cohere Rerank 3.5 model (cohere.rerank-v3-5:0) invoked during a reranked
        // Retrieve — both are foundation-model/* ARNs in this Region.
        actions: ['bedrock:InvokeModel'],
        resources: [`arn:aws:bedrock:${this.region}::foundation-model/*`],
      })
    );

    // Reranking during Retrieve: the KB service role (NOT the caller) performs the
    // bedrock:Rerank call, so it must be authorized for that action. Without this,
    // a reranked Retrieve fails with "is not authorized to perform: bedrock:Rerank
    // because no identity-based policy allows the bedrock:Rerank action". The Rerank
    // action does not support resource-level scoping, so Resource must be "*".
    role.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: ['bedrock:Rerank'],
        resources: ['*'],
      })
    );

    return role;
  }

  private vectorKbConfig(): bedrock.CfnKnowledgeBase.KnowledgeBaseConfigurationProperty {
    return {
      type: 'VECTOR',
      vectorKnowledgeBaseConfiguration: {
        embeddingModelArn: `arn:aws:bedrock:${this.region}::foundation-model/amazon.titan-embed-text-v2:0`,
        embeddingModelConfiguration: {
          bedrockEmbeddingModelConfiguration: { dimensions: 1024, embeddingDataType: 'FLOAT32' },
        },
      },
    };
  }

  private s3VectorStorageConfig(
    vectorBucketArn: string,
    indexName: string
  ): bedrock.CfnKnowledgeBase.StorageConfigurationProperty {
    return {
      type: 'S3_VECTORS',
      s3VectorsConfiguration: { vectorBucketArn, indexName },
    };
  }

  private createSyncTrigger(id: string, kbRef: string, dataSourceRef: string): void {
    const role = new iam.Role(this, `${id}Role`, {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole'),
      ],
    });
    role.addToPolicy(
      new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        actions: [
          'bedrock:StartIngestionJob',
          'bedrock:GetIngestionJob',
          'bedrock:ListIngestionJobs',
        ],
        resources: [`arn:aws:bedrock:${this.region}:${this.account}:knowledge-base/*`],
      })
    );

    const fn = new lambda.Function(this, `${id}Fn`, {
      runtime: lambda.Runtime.PYTHON_3_12,
      handler: 'index.handler',
      role,
      timeout: Duration.seconds(240),
      // nosemgrep: missing-template-string-indicator - {variable} below is valid Python f-string inside backtick, not a JS template literal
      code: lambda.Code.fromInline(`
import boto3, os, json, urllib3

SUCCESS = 'SUCCESS'
FAILED  = 'FAILED'

def send(event, context, status, data={}):
    body = json.dumps({
        'Status': status,
        'Reason': 'See CloudWatch',
        'PhysicalResourceId': event.get('PhysicalResourceId', context.log_stream_name),
        'StackId': event['StackId'],
        'RequestId': event['RequestId'],
        'LogicalResourceId': event['LogicalResourceId'],
        'Data': data,
    })
    http = urllib3.PoolManager()
    http.request('PUT', event['ResponseURL'],
                 body=body,
                 headers={'Content-Type': '', 'Content-Length': str(len(body))})

def handler(event, context):
    try:
        if event['RequestType'] == 'Delete':
            send(event, context, SUCCESS)
            return
        kb_id = event['ResourceProperties']['KnowledgeBaseId']
        ds_id = event['ResourceProperties']['DataSourceId'].replace(kb_id, '').replace('|', '')
        client = boto3.client('bedrock-agent', region_name=os.environ['AWS_REGION'])
        try:
            job = client.start_ingestion_job(knowledgeBaseId=kb_id, dataSourceId=ds_id)
            print(f"Started ingestion job {job['ingestionJob']['ingestionJobId']} kb={kb_id} ds={ds_id}")
            send(event, context, SUCCESS, {'IngestionJobId': job['ingestionJob']['ingestionJobId']})
        except client.exceptions.ConflictException as e:
            # A job is already running on this data source — the sync we wanted is
            # already happening, so this is a no-op success, not a failure.
            print(f"Ingestion already in progress kb={kb_id} ds={ds_id}; success (no-op): {e}")
            send(event, context, SUCCESS, {'IngestionJobId': 'already-running'})
        except client.exceptions.ResourceNotFoundException as e:
            # During a DataSource REPLACEMENT (e.g. a chunking-strategy change) this
            # trigger can fire against the OLD data source id while CFN deletes it.
            # The replacement data source has its own trigger; a missing source here
            # is benign and must NOT fail the stack (else the whole update rolls back).
            print(f"Data source not found (likely mid-replacement) kb={kb_id} ds={ds_id}; success (no-op): {e}")
            send(event, context, SUCCESS, {'IngestionJobId': 'data-source-absent'})
    except Exception as e:
        # Log the real error — the CFN Reason field only ever says "See CloudWatch".
        import traceback
        # nosemgrep: missing-template-string-indicator — real Python f-string (embedded Lambda src), intentional
        print(f"OpSync ingestion trigger FAILED: {e}\\n{traceback.format_exc()}")
        send(event, context, FAILED, {'Error': str(e)})
`),
    });

    const trigger = new CustomResource(this, id, {
      serviceToken: fn.functionArn,
      properties: { KnowledgeBaseId: kbRef, DataSourceId: dataSourceRef },
    });
    trigger.node.addDependency(fn);
  }
}
